"""
Medical PDF Generator
Generates professional medical documents:
1. Insurance Claim PDF (ICD-10 coded)
2. Clinical Notes PDF (structured documentation)
3. Health Record Update PDF (longitudinal history)
"""
import os
import logging
from datetime import datetime
from io import BytesIO
from typing import Dict, List
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

logger = logging.getLogger(__name__)


class PDFGenerator:
    """Generate professional medical PDFs"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        logger.info("✓ PDF generator initialized")
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1a56db'),
            spaceAfter=12,
            alignment=TA_CENTER
        ))
        
        # Section header
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e40af'),
            spaceBefore=12,
            spaceAfter=6,
            borderWidth=1,
            borderColor=colors.HexColor('#3b82f6'),
            borderPadding=5,
            backColor=colors.HexColor('#eff6ff')
        ))
        
        # Warning style
        self.styles.add(ParagraphStyle(
            name='Warning',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#dc2626'),
            backColor=colors.HexColor('#fee2e2'),
            borderWidth=1,
            borderColor=colors.HexColor('#dc2626'),
            borderPadding=8,
            spaceBefore=6,
            spaceAfter=6
        ))
    
    def generate_insurance_claim(
        self,
        patient_data: Dict,
        analysis_data: Dict,
        doctor_data: Dict,
        fraud_data: Dict = None
    ) -> bytes:
        """
        Generate insurance claim PDF with ICD-10 codes.
        
        Args:
            patient_data: {"name": "...", "id": "...", "dob": "...", "phone": "..."}
            analysis_data: {"conditions": [...], "biomarkers": {...}, "risk_score": 85, ...}
            doctor_data: {"name": "...", "license": "...", "specialty": "...", "hospital": "..."}
            fraud_data: {"fraud_score": 15, "flags": [...], "is_suspicious": False}
            
        Returns:
            bytes: PDF file content
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        
        # Title
        story.append(Paragraph("MEDICAL INSURANCE CLAIM", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        # Claim metadata
        claim_date = datetime.now().strftime("%B %d, %Y")
        claim_id = f"MC-{datetime.now().strftime('%Y%m%d%H%M%S')}"
        
        metadata_data = [
            ["Claim ID:", claim_id, "Claim Date:", claim_date],
            ["Generated By:", "MediChain AI", "Status:", "PENDING REVIEW"]
        ]
        
        metadata_table = Table(metadata_data, colWidths=[1.5*inch, 2*inch, 1.5*inch, 2*inch])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f3f4f6')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(metadata_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Patient Information
        story.append(Paragraph("PATIENT INFORMATION", self.styles['SectionHeader']))
        patient_info = [
            ["Full Name:", patient_data.get("name", "N/A")],
            ["Patient ID:", patient_data.get("id", "N/A")],
            ["Date of Birth:", patient_data.get("dob", "N/A")],
            ["Contact:", patient_data.get("phone", "N/A")]
        ]
        patient_table = Table(patient_info, colWidths=[2*inch, 5*inch])
        patient_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'TOP')
        ]))
        story.append(patient_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Doctor Information
        story.append(Paragraph("ATTENDING PHYSICIAN", self.styles['SectionHeader']))
        doctor_info = [
            ["Physician Name:", doctor_data.get("name", "N/A")],
            ["License Number:", doctor_data.get("license", "N/A")],
            ["Specialty:", doctor_data.get("specialty", "N/A")],
            ["Hospital/Clinic:", doctor_data.get("hospital", "N/A")]
        ]
        doctor_table = Table(doctor_info, colWidths=[2*inch, 5*inch])
        doctor_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(doctor_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Diagnosis with ICD-10 Codes
        story.append(Paragraph("DIAGNOSIS & ICD-10 CODES", self.styles['SectionHeader']))
        
        conditions = analysis_data.get("conditions", [])
        icd10_codes = self._extract_icd10_codes(conditions)
        
        diagnosis_data = [["ICD-10 Code", "Diagnosis Description", "Severity"]]
        for code, description, severity in icd10_codes:
            diagnosis_data.append([code, description, severity])
        
        diagnosis_table = Table(diagnosis_data, colWidths=[1.5*inch, 4*inch, 1.5*inch])
        diagnosis_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
        ]))
        story.append(diagnosis_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Clinical Findings
        story.append(Paragraph("CLINICAL FINDINGS", self.styles['SectionHeader']))
        
        biomarkers = analysis_data.get("biomarkers", {})
        findings_data = [["Test Name", "Result", "Reference Range", "Status"]]
        
        for test_name, value in list(biomarkers.items())[:10]:
            # Simplified - in production, would have actual reference ranges
            findings_data.append([test_name, str(value), "See report", "Abnormal"])
        
        findings_table = Table(findings_data, colWidths=[2.5*inch, 1.5*inch, 2*inch, 1*inch])
        findings_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
        ]))
        story.append(findings_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Risk Assessment
        story.append(Paragraph("RISK ASSESSMENT", self.styles['SectionHeader']))
        risk_score = analysis_data.get("risk_score", 50)
        risk_level = analysis_data.get("risk_level", "medium")
        
        risk_color = colors.HexColor('#22c55e') if risk_level == "low" else \
                     colors.HexColor('#eab308') if risk_level == "medium" else \
                     colors.HexColor('#ef4444')
        
        risk_data = [
            ["Risk Score:", f"{risk_score}/100", "Risk Level:", risk_level.upper()],
            ["Specialist Recommended:", analysis_data.get("specialist", "General Practitioner"), "Urgency:", analysis_data.get("urgency", "low").upper()]
        ]
        
        risk_table = Table(risk_data, colWidths=[2*inch, 1.5*inch, 2*inch, 1.5*inch])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e5e7eb')),
            ('BACKGROUND', (1, 0), (1, 0), risk_color),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(risk_table)
        story.append(Spacer(1, 0.2*inch))
        
        # Fraud Detection Certificate
        if fraud_data:
            story.append(Paragraph("FRAUD DETECTION CERTIFICATE", self.styles['SectionHeader']))
            
            fraud_score = fraud_data.get("fraud_score", 0)
            is_suspicious = fraud_data.get("is_suspicious", False)
            
            fraud_status = "⚠️ SUSPICIOUS" if is_suspicious else "✓ VERIFIED"
            fraud_color = colors.HexColor('#ef4444') if is_suspicious else colors.HexColor('#22c55e')
            
            fraud_info = [
                ["Fraud Score:", f"{fraud_score}/100", "Status:", fraud_status],
                ["Confidence:", f"{fraud_data.get('confidence', 50)}%", "Flags Detected:", str(fraud_data.get('total_flags', 0))]
            ]
            
            fraud_table = Table(fraud_info, colWidths=[2*inch, 1.5*inch, 2*inch, 1.5*inch])
            fraud_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e5e7eb')),
                ('BACKGROUND', (3, 0), (3, 0), fraud_color),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
            ]))
            story.append(fraud_table)
            
            if is_suspicious:
                warning_text = f"<b>WARNING:</b> This claim has been flagged for potential fraud. {fraud_data.get('total_flags', 0)} physiological impossibilities detected. Manual review required."
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph(warning_text, self.styles['Warning']))
            
            story.append(Spacer(1, 0.2*inch))
        
        # Blockchain Verification
        story.append(Paragraph("BLOCKCHAIN VERIFICATION", self.styles['SectionHeader']))
        
        record_id = analysis_data.get("record_id", "N/A")
        ipfs_cid = analysis_data.get("ipfs_cid", "N/A")
        record_hash = analysis_data.get("record_hash", "N/A")
        
        blockchain_info = [
            ["Record ID:", record_id[:32] + "..." if len(record_id) > 32 else record_id],
            ["IPFS CID:", ipfs_cid[:32] + "..." if len(ipfs_cid) > 32 else ipfs_cid],
            ["Record Hash:", record_hash[:32] + "..." if len(record_hash) > 32 else record_hash],
            ["Verification URL:", f"{os.getenv('PUBLIC_WEBHOOK_URL', 'https://medichain.app')}/verify/{record_id}"]
        ]
        
        blockchain_table = Table(blockchain_info, colWidths=[2*inch, 5*inch])
        blockchain_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e5e7eb')),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(blockchain_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Footer
        footer_text = f"""
        <para align=center fontSize=8 textColor=#6b7280>
        This claim is generated by MediChain AI and secured on blockchain.<br/>
        All medical data is encrypted and tamper-proof. Verify authenticity at the URL above.<br/>
        Generated on {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
        </para>
        """
        story.append(Paragraph(footer_text, self.styles['Normal']))
        
        # Build PDF
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        logger.info(f"✓ Generated insurance claim PDF ({len(pdf_bytes)} bytes)")
        return pdf_bytes
    
    def _extract_icd10_codes(self, conditions: List[str]) -> List[tuple]:
        """
        Extract or map conditions to ICD-10 codes.
        In production, this would use a proper medical ontology.
        """
        # Simplified ICD-10 mapping
        icd10_map = {
            "diabetes": ("E11.9", "Type 2 Diabetes Mellitus", "Moderate"),
            "type 2 diabetes": ("E11.9", "Type 2 Diabetes Mellitus", "Moderate"),
            "hypertension": ("I10", "Essential Hypertension", "Moderate"),
            "high blood pressure": ("I10", "Essential Hypertension", "Moderate"),
            "hyperlipidemia": ("E78.5", "Hyperlipidemia", "Mild"),
            "high cholesterol": ("E78.0", "Pure Hypercholesterolemia", "Mild"),
            "chronic kidney disease": ("N18.9", "Chronic Kidney Disease", "Severe"),
            "kidney disease": ("N18.9", "Chronic Kidney Disease", "Moderate"),
            "coronary artery disease": ("I25.10", "Coronary Artery Disease", "Severe"),
            "heart disease": ("I51.9", "Heart Disease, Unspecified", "Moderate"),
            "obesity": ("E66.9", "Obesity, Unspecified", "Mild"),
            "anemia": ("D64.9", "Anemia, Unspecified", "Mild")
        }
        
        results = []
        for condition in conditions:
            condition_lower = condition.lower()
            
            # Try exact match
            if condition_lower in icd10_map:
                results.append(icd10_map[condition_lower])
            else:
                # Try partial match
                for key, value in icd10_map.items():
                    if key in condition_lower or condition_lower in key:
                        results.append(value)
                        break
                else:
                    # Default unknown condition
                    results.append(("R69", condition, "Unknown"))
        
        return results if results else [("R69", "Symptoms and signs, unspecified", "Unknown")]


def get_pdf_generator():
    """Get PDF generator instance"""
    return PDFGenerator()
