import pandas as pd
import numpy as np

print("=" * 70)
print("HEART DATASET")
print("=" * 70)
df_heart = pd.read_csv('data/heart.csv')
print(f"Shape: {df_heart.shape}")
print(f"Columns: {list(df_heart.columns)}")
print(f"\nFirst 3 rows:")
print(df_heart.head(3))
print(f"\nData types:")
print(df_heart.dtypes)
print(f"\nTarget column (last): {df_heart.columns[-1]}")
print(f"Target values: {df_heart.iloc[:, -1].unique()}")
print(f"Missing values: {df_heart.isnull().sum().sum()}")

print("\n" + "=" * 70)
print("DIABETES DATASET")
print("=" * 70)
df_diabetes = pd.read_csv('data/diabetes.csv')
print(f"Shape: {df_diabetes.shape}")
print(f"Columns: {list(df_diabetes.columns)}")
print(f"\nFirst 3 rows:")
print(df_diabetes.head(3))
print(f"\nData types:")
print(df_diabetes.dtypes)
print(f"\nTarget column (last): {df_diabetes.columns[-1]}")
print(f"Target values: {df_diabetes.iloc[:, -1].unique()}")
print(f"Missing values: {df_diabetes.isnull().sum().sum()}")

print("\n" + "=" * 70)
print("KIDNEY DATASET")
print("=" * 70)
df_kidney = pd.read_csv('data/kidney_disease.csv')
print(f"Shape: {df_kidney.shape}")
print(f"Columns: {list(df_kidney.columns)}")
print(f"\nFirst 3 rows:")
print(df_kidney.head(3))
print(f"\nData types:")
print(df_kidney.dtypes)
print(f"\nTarget column (last): {df_kidney.columns[-1]}")
print(f"Target values: {df_kidney.iloc[:, -1].unique()}")
print(f"Missing values: {df_kidney.isnull().sum().sum()}")
